name = "CytoZoo"
uuid = "ff4ab244-b974-488c-a5cc-2c6c87261b37"
version = "0.0.1"
authors = ["Kyle Beggs (beggskw@gmail.com) and contributors"]

[weakdeps]
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
Thunderbolt = "909927c2-98d5-4a67-bba9-79f03a9ad49b"

[extensions]
SciMLBaseExt = "SciMLBase"
ThunderboltExt = "Thunderbolt"

[compat]
SciMLBase = "2, 3"
julia = "1.10"

[extras]
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["JET", "OrdinaryDiffEq", "Test"]
