name = "CytoZoo"
uuid = "ff4ab244-b974-488c-a5cc-2c6c87261b37"
version = "0.0.1"
authors = ["Kyle Beggs (beggskw@gmail.com) and contributors"]

[weakdeps]
MTKCardiacCellModels = "cf70e313-3958-40e5-b5fe-3d717db61409"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
Thunderbolt = "909927c2-98d5-4a67-bba9-79f03a9ad49b"
TWorld = "7b3bcaa7-e8d1-4d64-97d9-61cb5d39b583"

[extensions]
MTKCardiacCellModelsExt = ["MTKCardiacCellModels", "ModelingToolkit", "SciMLBase"]
SciMLBaseExt = "SciMLBase"
ThunderboltExt = "Thunderbolt"
ThunderboltTWorldExt = ["Thunderbolt", "TWorld"]
TWorldExt = "TWorld"

[compat]
julia = "1.10"

[extras]
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["JET", "OrdinaryDiffEq", "Test"]
